/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bookman' at '11/16/16 4:01 PM' with Gradle 3.3-20161019000016+0000
 *
 * @author bookman, @date 11/16/16 4:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
